#!/bin/bash

index=$1

./ahmm-s -i panels/panel${index} -s sample -e 1e-3 -g -p 0 10000 0.678 -p 1 438 0.322 --ne 10000 --window p 10 --traj 4 --gss 1 25188 100 0.001 0.15 > ahmms_outputs/ahmms_${index}
